"""Realistic seed dataset for Skill Atlas.

Everything here is hand-curated (no random generation) so the graph
reads as a plausible slice of a real learning/career catalog: skills
grouped into categories, courses that teach and require skills and
chain into each other as prerequisites, and roles that require skills
at a given importance/level.
"""

# (skill_id, name, category, description)
SKILLS = [
    # Programming Languages
    ("python", "Python", "Programming Languages", "General-purpose language widely used in backend, data and ML work."),
    ("javascript", "JavaScript", "Programming Languages", "The language of the web browser, also used server-side via Node.js."),
    ("typescript", "TypeScript", "Programming Languages", "A statically typed superset of JavaScript."),
    ("go", "Go", "Programming Languages", "Compiled language popular for backend services and infrastructure tooling."),
    ("java", "Java", "Programming Languages", "Long-standing enterprise and Android language."),
    ("sql", "SQL", "Programming Languages", "Query language for relational databases."),
    ("rust", "Rust", "Programming Languages", "Systems language focused on memory safety and performance."),
    ("bash_scripting", "Bash Scripting", "Programming Languages", "Shell scripting for automation on Unix-like systems."),
    # Web & Frameworks
    ("react", "React", "Web & Frameworks", "Component-based UI library for building web frontends."),
    ("nodejs", "Node.js", "Web & Frameworks", "JavaScript runtime for building backend services."),
    ("fastapi", "FastAPI", "Web & Frameworks", "Modern Python web framework for building APIs."),
    ("django", "Django", "Web & Frameworks", "Batteries-included Python web framework."),
    ("express", "Express.js", "Web & Frameworks", "Minimal Node.js web framework for building APIs."),
    ("nextjs", "Next.js", "Web & Frameworks", "React framework with server rendering and routing built in."),
    ("vue", "Vue.js", "Web & Frameworks", "Approachable frontend framework."),
    ("rest_apis", "REST API Design", "Web & Frameworks", "Designing resource-oriented HTTP APIs."),
    ("graphql", "GraphQL", "Web & Frameworks", "Query language and runtime for client-driven APIs."),
    # Data & ML
    ("statistics", "Statistics", "Data & ML", "Probability and inference, the foundation of data analysis."),
    ("machine_learning", "Machine Learning", "Data & ML", "Building models that learn patterns from data."),
    ("data_visualization", "Data Visualization", "Data & ML", "Communicating data findings visually."),
    ("pandas", "Pandas", "Data & ML", "Python library for tabular data manipulation."),
    ("etl", "ETL Pipelines", "Data & ML", "Extracting, transforming and loading data between systems."),
    ("data_warehousing", "Data Warehousing", "Data & ML", "Designing systems for large-scale analytical storage."),
    ("deep_learning", "Deep Learning", "Data & ML", "Neural network based machine learning."),
    ("nlp", "Natural Language Processing", "Data & ML", "Modeling and understanding human language with computers."),
    ("data_modeling", "Data Modeling", "Data & ML", "Structuring data for correctness and query efficiency."),
    # Cloud & DevOps
    ("aws", "AWS", "Cloud & DevOps", "Amazon's cloud computing platform."),
    ("docker", "Docker", "Cloud & DevOps", "Packaging applications into portable containers."),
    ("kubernetes", "Kubernetes", "Cloud & DevOps", "Orchestrating containerized workloads at scale."),
    ("ci_cd", "CI/CD", "Cloud & DevOps", "Automating build, test and deployment pipelines."),
    ("linux", "Linux Administration", "Cloud & DevOps", "Operating, securing and troubleshooting Linux systems."),
    ("terraform", "Terraform", "Cloud & DevOps", "Declarative infrastructure-as-code tooling."),
    ("computer_networking", "Computer Networking", "Cloud & DevOps", "How data moves between systems: TCP/IP, DNS, load balancing."),
    ("monitoring_observability", "Monitoring & Observability", "Cloud & DevOps", "Metrics, logs and traces for understanding live systems."),
    ("git", "Git & Version Control", "Cloud & DevOps", "Tracking and collaborating on code changes."),
    # Design & UX
    ("ui_design", "UI Design", "Design & UX", "Visual design of interfaces."),
    ("ux_research", "UX Research", "Design & UX", "Methods for understanding user needs and behavior."),
    ("figma", "Figma", "Design & UX", "Collaborative interface design tool."),
    ("design_systems", "Design Systems", "Design & UX", "Reusable components and standards for consistent UI."),
    ("typography", "Typography", "Design & UX", "The craft of arranging type for legibility and tone."),
    ("prototyping", "Prototyping", "Design & UX", "Building interactive mockups to validate ideas quickly."),
    ("accessibility", "Accessibility (a11y)", "Design & UX", "Designing usable experiences for people with disabilities."),
    # Product
    ("product_strategy", "Product Strategy", "Product", "Defining what to build and why, aligned to business goals."),
    ("user_research", "User Research", "Product", "Talking to and observing users to inform product decisions."),
    ("roadmapping", "Roadmapping", "Product", "Sequencing and communicating product plans over time."),
    ("market_analysis", "Market Analysis", "Product", "Assessing competitors, market size and positioning."),
    ("ab_testing", "A/B Testing", "Product", "Running controlled experiments to validate product changes."),
    # Security
    ("application_security", "Application Security", "Security", "Finding and preventing vulnerabilities in software."),
    ("cryptography_basics", "Cryptography Basics", "Security", "Core concepts behind encryption, hashing and signatures."),
    ("threat_modeling", "Threat Modeling", "Security", "Systematically identifying and prioritizing security risks."),
    ("identity_access_management", "Identity & Access Management", "Security", "Controlling who can access what, and how identity is verified."),
    # Soft Skills
    ("communication", "Communication", "Soft Skills", "Clearly conveying ideas to varied audiences."),
    ("project_management", "Project Management", "Soft Skills", "Planning and coordinating work to hit goals on time."),
    ("agile_scrum", "Agile & Scrum", "Soft Skills", "Iterative delivery frameworks for product teams."),
    ("technical_writing", "Technical Writing", "Soft Skills", "Writing clear documentation and technical content."),
    ("public_speaking", "Public Speaking", "Soft Skills", "Presenting ideas confidently to an audience."),
    ("mentoring", "Mentoring & Leadership", "Soft Skills", "Growing the skills of the people around you."),
    ("stakeholder_management", "Stakeholder Management", "Soft Skills", "Aligning people with competing priorities."),
    # CS Fundamentals
    ("data_structures_algorithms", "Data Structures & Algorithms", "CS Fundamentals", "Core building blocks for efficient software."),
    ("discrete_math", "Discrete Math", "CS Fundamentals", "Mathematical foundations behind computer science."),
    ("systems_design", "Systems Design", "CS Fundamentals", "Designing software architecture that scales and stays reliable."),
    ("databases_theory", "Database Theory", "CS Fundamentals", "Relational theory, normalization, transactions and indexing."),
    ("distributed_systems", "Distributed Systems", "CS Fundamentals", "Designing systems that span multiple machines reliably."),
]

# (course_id, title, provider, level, duration_hours, url, teaches[], requires[])
COURSES = [
    ("python_fundamentals", "Python Fundamentals", "Codecademy", "Beginner", 12, "https://example.com/courses/python-fundamentals", ["python"], []),
    ("python_intermediate", "Intermediate Python", "Codecademy", "Intermediate", 16, "https://example.com/courses/python-intermediate", ["python", "data_structures_algorithms"], ["python"]),
    ("python_for_data_analysis", "Python for Data Analysis", "Coursera", "Intermediate", 14, "https://example.com/courses/python-data-analysis", ["pandas", "data_visualization"], ["python"]),
    ("statistics_for_data_science", "Statistics for Data Science", "edX", "Beginner", 10, "https://example.com/courses/statistics-for-ds", ["statistics"], []),
    ("intro_machine_learning", "Introduction to Machine Learning", "Coursera", "Intermediate", 20, "https://example.com/courses/intro-ml", ["machine_learning"], ["python", "statistics"]),
    ("deep_learning_specialization", "Deep Learning Specialization", "Coursera", "Advanced", 30, "https://example.com/courses/deep-learning", ["deep_learning", "nlp"], ["machine_learning"]),
    ("sql_fundamentals", "SQL Fundamentals", "Codecademy", "Beginner", 8, "https://example.com/courses/sql-fundamentals", ["sql"], []),
    ("data_modeling_essentials", "Data Modeling Essentials", "Pluralsight", "Intermediate", 10, "https://example.com/courses/data-modeling", ["data_modeling", "databases_theory"], ["sql"]),
    ("data_warehousing_etl", "Data Warehousing & ETL", "Pluralsight", "Intermediate", 14, "https://example.com/courses/data-warehousing-etl", ["etl", "data_warehousing"], ["sql"]),
    ("javascript_fundamentals", "JavaScript Fundamentals", "freeCodeCamp", "Beginner", 10, "https://example.com/courses/javascript-fundamentals", ["javascript"], []),
    ("typescript_for_js_devs", "TypeScript for JavaScript Developers", "freeCodeCamp", "Intermediate", 8, "https://example.com/courses/typescript-for-js-devs", ["typescript"], ["javascript"]),
    ("react_essentials", "React Essentials", "Udemy", "Intermediate", 16, "https://example.com/courses/react-essentials", ["react"], ["javascript"]),
    ("advanced_react_patterns", "Advanced React Patterns", "Udemy", "Advanced", 12, "https://example.com/courses/advanced-react-patterns", ["react", "design_systems"], ["react"]),
    ("nextjs_fullstack", "Full-Stack Next.js", "Udemy", "Advanced", 14, "https://example.com/courses/nextjs-fullstack", ["nextjs", "rest_apis"], ["react"]),
    ("nodejs_backend", "Node.js for Backend Development", "Udemy", "Intermediate", 14, "https://example.com/courses/nodejs-backend", ["nodejs", "rest_apis"], ["javascript"]),
    ("express_api_development", "API Development with Express", "Udemy", "Intermediate", 10, "https://example.com/courses/express-api", ["express", "rest_apis"], ["nodejs"]),
    ("fastapi_for_python_devs", "FastAPI for Python Developers", "O'Reilly", "Intermediate", 10, "https://example.com/courses/fastapi", ["fastapi", "rest_apis"], ["python"]),
    ("graphql_api_design", "GraphQL API Design", "O'Reilly", "Advanced", 8, "https://example.com/courses/graphql", ["graphql"], ["rest_apis"]),
    ("go_fundamentals", "Go Fundamentals", "O'Reilly", "Beginner", 12, "https://example.com/courses/go-fundamentals", ["go"], []),
    ("systems_design_for_engineers", "Systems Design for Engineers", "Internal Academy", "Advanced", 18, "https://example.com/courses/systems-design", ["systems_design", "distributed_systems"], ["data_structures_algorithms"]),
    ("java_fundamentals", "Java Fundamentals", "Pluralsight", "Beginner", 14, "https://example.com/courses/java-fundamentals", ["java"], []),
    ("discrete_math_for_cs", "Discrete Math for Computer Science", "edX", "Beginner", 10, "https://example.com/courses/discrete-math", ["discrete_math"], []),
    ("data_structures_deep_dive", "Data Structures Deep Dive", "Internal Academy", "Advanced", 20, "https://example.com/courses/data-structures-deep-dive", ["data_structures_algorithms"], ["discrete_math"]),
    ("git_version_control", "Git & Version Control", "freeCodeCamp", "Beginner", 4, "https://example.com/courses/git", ["git"], []),
    ("linux_command_line", "Linux Command Line Basics", "Linux Academy", "Beginner", 8, "https://example.com/courses/linux-basics", ["linux", "bash_scripting"], []),
    ("docker_fundamentals", "Docker Fundamentals", "Linux Academy", "Beginner", 10, "https://example.com/courses/docker-fundamentals", ["docker"], ["linux"]),
    ("kubernetes_in_production", "Kubernetes in Production", "Linux Academy", "Advanced", 20, "https://example.com/courses/kubernetes-production", ["kubernetes"], ["docker"]),
    ("aws_cloud_practitioner", "AWS Cloud Practitioner", "AWS Training", "Beginner", 12, "https://example.com/courses/aws-cloud-practitioner", ["aws"], []),
    ("aws_solutions_architect", "AWS Solutions Architect", "AWS Training", "Advanced", 24, "https://example.com/courses/aws-solutions-architect", ["aws", "systems_design"], ["aws"]),
    ("terraform_infrastructure_as_code", "Terraform: Infrastructure as Code", "HashiCorp Learn", "Intermediate", 12, "https://example.com/courses/terraform", ["terraform"], ["aws"]),
    ("ci_cd_pipelines", "Building CI/CD Pipelines", "Internal Academy", "Intermediate", 10, "https://example.com/courses/ci-cd", ["ci_cd"], ["git", "docker"]),
    ("monitoring_and_observability", "Monitoring & Observability", "Internal Academy", "Intermediate", 8, "https://example.com/courses/monitoring", ["monitoring_observability"], ["linux"]),
    ("computer_networking_basics", "Computer Networking Basics", "edX", "Beginner", 10, "https://example.com/courses/networking-basics", ["computer_networking"], []),
    ("application_security_fundamentals", "Application Security Fundamentals", "O'Reilly", "Intermediate", 12, "https://example.com/courses/appsec-fundamentals", ["application_security"], ["rest_apis"]),
    ("cryptography_basics_course", "Cryptography Basics", "edX", "Intermediate", 10, "https://example.com/courses/cryptography-basics", ["cryptography_basics"], ["discrete_math"]),
    ("threat_modeling_workshop", "Threat Modeling Workshop", "Internal Academy", "Advanced", 8, "https://example.com/courses/threat-modeling", ["threat_modeling"], ["application_security"]),
    ("identity_access_management_course", "Identity & Access Management", "O'Reilly", "Intermediate", 8, "https://example.com/courses/iam", ["identity_access_management"], ["application_security"]),
    ("ui_design_foundations", "UI Design Foundations", "Coursera", "Beginner", 10, "https://example.com/courses/ui-design-foundations", ["ui_design", "typography"], []),
    ("figma_for_product_design", "Figma for Product Design", "Coursera", "Beginner", 8, "https://example.com/courses/figma", ["figma", "prototyping"], ["ui_design"]),
    ("design_systems_at_scale", "Design Systems at Scale", "Internal Academy", "Advanced", 12, "https://example.com/courses/design-systems", ["design_systems"], ["figma"]),
    ("ux_research_methods", "UX Research Methods", "Coursera", "Intermediate", 12, "https://example.com/courses/ux-research", ["ux_research", "user_research"], []),
    ("accessibility_in_design", "Accessibility in Design", "Coursera", "Intermediate", 8, "https://example.com/courses/accessibility", ["accessibility"], ["ui_design"]),
    ("product_strategy_essentials", "Product Strategy Essentials", "Reforge", "Intermediate", 10, "https://example.com/courses/product-strategy", ["product_strategy", "roadmapping"], []),
    ("ab_testing_for_product_teams", "A/B Testing for Product Teams", "Reforge", "Intermediate", 8, "https://example.com/courses/ab-testing", ["ab_testing"], ["statistics"]),
    ("stakeholder_management_course", "Stakeholder Management", "LinkedIn Learning", "Beginner", 6, "https://example.com/courses/stakeholder-management", ["stakeholder_management", "communication"], []),
    ("agile_scrum_certification", "Agile & Scrum Certification", "Scrum Alliance", "Beginner", 8, "https://example.com/courses/agile-scrum", ["agile_scrum", "project_management"], []),
    ("technical_writing_workshop", "Technical Writing Workshop", "LinkedIn Learning", "Beginner", 6, "https://example.com/courses/technical-writing", ["technical_writing"], []),
    ("public_speaking_for_engineers", "Public Speaking for Engineers", "LinkedIn Learning", "Beginner", 6, "https://example.com/courses/public-speaking", ["public_speaking"], []),
    ("mentoring_and_leadership", "Mentoring & Leadership", "Internal Academy", "Intermediate", 8, "https://example.com/courses/mentoring", ["mentoring"], ["communication"]),
    ("market_analysis_for_pms", "Market Analysis for Product Managers", "Reforge", "Intermediate", 8, "https://example.com/courses/market-analysis", ["market_analysis"], ["product_strategy"]),
]

# (before_course_id, after_course_id) -- before must be completed first
COURSE_PREREQUISITES = [
    ("python_fundamentals", "python_intermediate"),
    ("python_intermediate", "python_for_data_analysis"),
    ("python_intermediate", "fastapi_for_python_devs"),
    ("python_intermediate", "systems_design_for_engineers"),
    ("python_for_data_analysis", "intro_machine_learning"),
    ("statistics_for_data_science", "intro_machine_learning"),
    ("intro_machine_learning", "deep_learning_specialization"),
    ("sql_fundamentals", "data_modeling_essentials"),
    ("data_modeling_essentials", "data_warehousing_etl"),
    ("javascript_fundamentals", "typescript_for_js_devs"),
    ("javascript_fundamentals", "react_essentials"),
    ("javascript_fundamentals", "nodejs_backend"),
    ("react_essentials", "advanced_react_patterns"),
    ("react_essentials", "nextjs_fullstack"),
    ("nodejs_backend", "express_api_development"),
    ("rest_apis_placeholder", "graphql_api_design"),  # replaced below
    ("discrete_math_for_cs", "data_structures_deep_dive"),
    ("linux_command_line", "docker_fundamentals"),
    ("docker_fundamentals", "kubernetes_in_production"),
    ("docker_fundamentals", "ci_cd_pipelines"),
    ("aws_cloud_practitioner", "aws_solutions_architect"),
    ("aws_cloud_practitioner", "terraform_infrastructure_as_code"),
    ("application_security_fundamentals", "threat_modeling_workshop"),
    ("application_security_fundamentals", "identity_access_management_course"),
    ("ui_design_foundations", "figma_for_product_design"),
    ("ui_design_foundations", "accessibility_in_design"),
    ("figma_for_product_design", "design_systems_at_scale"),
    ("product_strategy_essentials", "market_analysis_for_pms"),
]
# express_api_development and fastapi_for_python_devs both teach rest_apis;
# graphql builds conceptually on REST API design, so it follows whichever
# REST course a learner path already includes -- modeled as following the
# Express course specifically to keep the chain concrete.
COURSE_PREREQUISITES = [
    p for p in COURSE_PREREQUISITES if p[0] != "rest_apis_placeholder"
] + [("express_api_development", "graphql_api_design")]

# (role_id, title, industry, seniority, description, requirements[])
# each requirement: (skill_id, importance["core"|"nice-to-have"], min_level)
ROLES = [
    ("frontend_engineer", "Frontend Engineer", "Software", "Mid", "Builds user-facing web interfaces and owns their quality.", [
        ("javascript", "core", "intermediate"), ("typescript", "core", "intermediate"),
        ("react", "core", "intermediate"), ("design_systems", "nice-to-have", "beginner"),
        ("accessibility", "nice-to-have", "intermediate"), ("git", "core", "beginner"),
    ]),
    ("backend_engineer", "Backend Engineer", "Software", "Mid", "Designs and operates the services behind the product.", [
        ("python", "core", "intermediate"), ("rest_apis", "core", "intermediate"),
        ("sql", "core", "intermediate"), ("systems_design", "core", "intermediate"),
        ("git", "core", "beginner"), ("docker", "nice-to-have", "beginner"),
    ]),
    ("fullstack_engineer", "Full-Stack Engineer", "Software", "Mid", "Comfortable across the whole web stack, front to back.", [
        ("javascript", "core", "intermediate"), ("react", "core", "intermediate"),
        ("nodejs", "core", "intermediate"), ("sql", "core", "beginner"),
        ("rest_apis", "core", "intermediate"), ("git", "core", "beginner"),
    ]),
    ("data_analyst", "Data Analyst", "Data", "Junior", "Turns raw data into decisions the business can act on.", [
        ("sql", "core", "intermediate"), ("pandas", "core", "intermediate"),
        ("data_visualization", "core", "intermediate"), ("statistics", "core", "beginner"),
        ("communication", "nice-to-have", "beginner"),
    ]),
    ("data_scientist", "Data Scientist", "Data", "Mid", "Builds statistical and ML models to answer harder questions.", [
        ("python", "core", "intermediate"), ("statistics", "core", "advanced"),
        ("machine_learning", "core", "intermediate"), ("pandas", "core", "intermediate"),
        ("data_visualization", "nice-to-have", "intermediate"), ("sql", "nice-to-have", "beginner"),
    ]),
    ("ml_engineer", "Machine Learning Engineer", "Data", "Senior", "Ships ML models as reliable production systems.", [
        ("python", "core", "advanced"), ("machine_learning", "core", "advanced"),
        ("deep_learning", "core", "intermediate"), ("systems_design", "core", "intermediate"),
        ("docker", "nice-to-have", "intermediate"), ("aws", "nice-to-have", "beginner"),
    ]),
    ("data_engineer", "Data Engineer", "Data", "Mid", "Builds the pipelines and warehouses other data roles depend on.", [
        ("sql", "core", "advanced"), ("etl", "core", "intermediate"),
        ("data_warehousing", "core", "intermediate"), ("python", "core", "intermediate"),
        ("aws", "nice-to-have", "intermediate"), ("data_modeling", "core", "intermediate"),
    ]),
    ("devops_engineer", "DevOps Engineer", "Infrastructure", "Mid", "Automates delivery and keeps environments consistent.", [
        ("linux", "core", "intermediate"), ("docker", "core", "intermediate"),
        ("kubernetes", "core", "intermediate"), ("ci_cd", "core", "intermediate"),
        ("terraform", "nice-to-have", "intermediate"), ("aws", "core", "intermediate"),
    ]),
    ("site_reliability_engineer", "Site Reliability Engineer", "Infrastructure", "Senior", "Keeps production systems fast, available and observable.", [
        ("linux", "core", "advanced"), ("kubernetes", "core", "advanced"),
        ("monitoring_observability", "core", "intermediate"), ("computer_networking", "core", "intermediate"),
        ("systems_design", "core", "advanced"), ("bash_scripting", "nice-to-have", "intermediate"),
    ]),
    ("security_engineer", "Security Engineer", "Security", "Mid", "Finds, fixes and prevents security weaknesses.", [
        ("application_security", "core", "advanced"), ("threat_modeling", "core", "intermediate"),
        ("cryptography_basics", "core", "intermediate"), ("identity_access_management", "core", "intermediate"),
        ("computer_networking", "nice-to-have", "intermediate"), ("linux", "nice-to-have", "intermediate"),
    ]),
    ("product_manager", "Product Manager", "Product", "Mid", "Decides what gets built and why, and rallies the team behind it.", [
        ("product_strategy", "core", "intermediate"), ("roadmapping", "core", "intermediate"),
        ("user_research", "core", "beginner"), ("ab_testing", "nice-to-have", "beginner"),
        ("stakeholder_management", "core", "intermediate"), ("communication", "core", "intermediate"),
    ]),
    ("ux_designer", "UX Designer", "Design", "Mid", "Researches and designs how the product should work.", [
        ("ui_design", "core", "intermediate"), ("ux_research", "core", "intermediate"),
        ("figma", "core", "intermediate"), ("prototyping", "core", "intermediate"),
        ("accessibility", "nice-to-have", "beginner"),
    ]),
    ("product_designer", "Product Designer", "Design", "Mid", "Owns visual and interaction design across the product.", [
        ("ui_design", "core", "intermediate"), ("figma", "core", "intermediate"),
        ("design_systems", "core", "intermediate"), ("prototyping", "nice-to-have", "intermediate"),
        ("user_research", "nice-to-have", "beginner"),
    ]),
    ("qa_test_engineer", "QA / Test Engineer", "Software", "Junior", "Protects product quality through testing and process.", [
        ("sql", "nice-to-have", "beginner"), ("javascript", "nice-to-have", "beginner"),
        ("git", "core", "beginner"), ("agile_scrum", "core", "beginner"),
        ("technical_writing", "nice-to-have", "beginner"), ("application_security", "nice-to-have", "beginner"),
    ]),
    ("engineering_manager", "Engineering Manager", "Software", "Senior", "Leads an engineering team's people and delivery.", [
        ("project_management", "core", "intermediate"), ("agile_scrum", "core", "intermediate"),
        ("mentoring", "core", "intermediate"), ("communication", "core", "advanced"),
        ("systems_design", "nice-to-have", "intermediate"), ("stakeholder_management", "nice-to-have", "intermediate"),
    ]),
    ("solutions_architect", "Solutions Architect", "Infrastructure", "Senior", "Designs system architecture across teams and platforms.", [
        ("systems_design", "core", "advanced"), ("aws", "core", "advanced"),
        ("distributed_systems", "core", "intermediate"), ("terraform", "nice-to-have", "intermediate"),
        ("computer_networking", "nice-to-have", "intermediate"), ("rest_apis", "core", "intermediate"),
    ]),
]

# (skill_a, skill_b, strength 0-1) -- undirected; stored as one directed
# edge and queried with an undirected MATCH pattern.
SKILL_RELATIONSHIPS = [
    ("python", "data_structures_algorithms", 0.7),
    ("python", "statistics", 0.5),
    ("python", "machine_learning", 0.6),
    ("statistics", "machine_learning", 0.8),
    ("machine_learning", "deep_learning", 0.9),
    ("machine_learning", "nlp", 0.7),
    ("deep_learning", "nlp", 0.8),
    ("pandas", "data_visualization", 0.7),
    ("pandas", "statistics", 0.6),
    ("pandas", "etl", 0.5),
    ("sql", "data_modeling", 0.8),
    ("sql", "databases_theory", 0.7),
    ("data_modeling", "databases_theory", 0.8),
    ("data_modeling", "etl", 0.6),
    ("etl", "data_warehousing", 0.9),
    ("data_warehousing", "databases_theory", 0.6),
    ("javascript", "typescript", 0.9),
    ("javascript", "react", 0.8),
    ("javascript", "nodejs", 0.8),
    ("typescript", "react", 0.6),
    ("react", "design_systems", 0.5),
    ("react", "nextjs", 0.8),
    ("nodejs", "express", 0.8),
    ("nodejs", "rest_apis", 0.6),
    ("express", "rest_apis", 0.7),
    ("fastapi", "rest_apis", 0.7),
    ("fastapi", "python", 0.7),
    ("graphql", "rest_apis", 0.6),
    ("go", "systems_design", 0.5),
    ("java", "systems_design", 0.4),
    ("systems_design", "distributed_systems", 0.9),
    ("systems_design", "data_structures_algorithms", 0.6),
    ("distributed_systems", "kubernetes", 0.5),
    ("distributed_systems", "aws", 0.5),
    ("discrete_math", "data_structures_algorithms", 0.8),
    ("discrete_math", "cryptography_basics", 0.6),
    ("linux", "bash_scripting", 0.8),
    ("linux", "docker", 0.7),
    ("docker", "kubernetes", 0.9),
    ("docker", "ci_cd", 0.7),
    ("kubernetes", "monitoring_observability", 0.6),
    ("ci_cd", "git", 0.6),
    ("aws", "terraform", 0.7),
    ("aws", "kubernetes", 0.5),
    ("aws", "systems_design", 0.5),
    ("terraform", "docker", 0.4),
    ("computer_networking", "linux", 0.5),
    ("computer_networking", "application_security", 0.5),
    ("application_security", "cryptography_basics", 0.7),
    ("application_security", "threat_modeling", 0.8),
    ("application_security", "identity_access_management", 0.7),
    ("threat_modeling", "identity_access_management", 0.6),
    ("ui_design", "typography", 0.7),
    ("ui_design", "figma", 0.8),
    ("figma", "prototyping", 0.8),
    ("figma", "design_systems", 0.6),
    ("design_systems", "accessibility", 0.5),
    ("ux_research", "user_research", 0.9),
    ("ux_research", "ui_design", 0.6),
    ("user_research", "product_strategy", 0.5),
    ("product_strategy", "roadmapping", 0.8),
    ("product_strategy", "market_analysis", 0.7),
    ("roadmapping", "stakeholder_management", 0.5),
    ("ab_testing", "statistics", 0.7),
    ("ab_testing", "product_strategy", 0.5),
    ("communication", "stakeholder_management", 0.7),
    ("communication", "public_speaking", 0.6),
    ("communication", "technical_writing", 0.5),
    ("agile_scrum", "project_management", 0.8),
    ("project_management", "mentoring", 0.5),
    ("mentoring", "communication", 0.6),
    ("data_visualization", "statistics", 0.6),
]
